apiVersion: v1
kind: Service
metadata:
  name: external-postgres
  namespace: default
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  clusterIP: None  

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-postgres
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.110  
    ports:
      - port: 5000