apiVersion: v1
kind: Service
metadata:
  name: external-postgres
  namespace: default
spec:
  type: ExternalName
  externalName: 192.168.1.110  # or db.example.com
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP