apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.114
  share: /srv/nfs/shared/kubeflow  # Path exported by your NFS server
reclaimPolicy: Retain
volumeBindingMode: Immediate
