- name: 
  hosts: first_node
  become: true

  tasks:
  - name: install
    ansible.builtin.shell: "helm repo add spark-operator https://kubeflow.github.io/spark-operator && helm repo update && helm install spark-operator spark-operator/spark-operator --namespace spark-operator --create-namespace"